### ISSUE TITLE
Can not oauth by login and password

### ISSUE THREAD

**Issue by shitpoet** [pyvim/vklancer#2]
Can not oauth by login and password:

```python
token = utils.oauth('***', '***')
```

`***` are real login and password.

```python
Traceback (most recent call last):
  File "/home/ors/bin/vk-checker.py", line 8, in <module>
    token = utils.oauth('***', '***')
  File "/home/ors/.local/lib/python2.7/site-packages/vklancer/utils.py", line 44, in oauth
    url = re.search(r'action="([^\"]+)"', response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Script worked, but suddenly stopped to work.

**Comment by dvemnt** [comment]
Hi, @shitpoet. I tried to auth with my credentials and it's worked. Maybe your account was blocked or have two-factor authentication (it's unsupported). You can check requests log. You need add those lines before function call.
```python
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by shitpoet** [comment]
You know, I tested it now, and it started to work again.

Yesterday I rewrote the script to use `vk` python package. And it worked. But maybe there was some temporary issue on vk side, and it was resolved while I was rewriting my script.
